This is makeindex, version 2.15 [MiKTeX 2.9.6500 64-bit] (kpathsea + Thai support).
Scanning style file ./paper.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file paper.acn....done (22 entries accepted, 0 rejected).
Sorting entries....done (96 comparisons).
Generating output file paper.acr....done (16 lines written, 0 warnings).
Output written in paper.acr.
Transcript written in paper.alg.
