package de.unihalle.informatik.bigdata.millionsongdataset.analysis.hadoop

import de.unihalle.informatik.bigdata.millionsongdataset.analysis.extensions.hadoop.*
import de.unihalle.informatik.bigdata.millionsongdataset.analysis.model.SongHandle
import java.io.DataInput
import java.io.DataOutput
import kotlin.properties.Delegates

class WritableSongHandle : SongHandle {

    override var artistFamiliarity: Double by Delegates.notNull()
    override var artistHotttnesss: Double by Delegates.notNull()
    override var artistId: String by Delegates.notNull()
    override var artistMbId: String by Delegates.notNull()
    override var artistPlaymeId: Int by Delegates.notNull()
    override var artist7DigitalId: Int by Delegates.notNull()
    override var artistLatitude: Double by Delegates.notNull()
    override var artistLongitude: Double by Delegates.notNull()
    override var artistLocation: String by Delegates.notNull()
    override var artistName: String by Delegates.notNull()
    override var release: String by Delegates.notNull()
    override var release7DigitalId: Int by Delegates.notNull()
    override var songId: String by Delegates.notNull()
    override var songHotttnesss: Double by Delegates.notNull()
    override var title: String by Delegates.notNull()
    override var track7DigitalId: Int by Delegates.notNull()
    override var similarArtists: Array<String> by Delegates.notNull()
    override var artistTerms: Array<String> by Delegates.notNull()
    override var artistTermsFrequency: DoubleArray by Delegates.notNull()
    override var artistTermsWeight: DoubleArray by Delegates.notNull()
    override var analysisSampleRate: Int by Delegates.notNull()
    override var audioMd5: String by Delegates.notNull()
    override var danceability: Double by Delegates.notNull()
    override var duration: Double by Delegates.notNull()
    override var fadeInEnd: Double by Delegates.notNull()
    override var energy: Double by Delegates.notNull()
    override var key: Int by Delegates.notNull()
    override var keyConfidence: Double by Delegates.notNull()
    override var loudness: Double by Delegates.notNull()
    override var mode: Int by Delegates.notNull()
    override var modeConfidence: Double by Delegates.notNull()
    override var fadeOutStart: Double by Delegates.notNull()
    override var tempo: Double by Delegates.notNull()
    override var timeSignature: Int by Delegates.notNull()
    override var timeSignatureConfidence: Double by Delegates.notNull()
    override var trackId: String by Delegates.notNull()
    override var segmentsStart: DoubleArray by Delegates.notNull()
    override var segmentsConfidence: DoubleArray by Delegates.notNull()
    override var segmentsPitches: DoubleArray by Delegates.notNull()
    override var segmentsTimbre: DoubleArray by Delegates.notNull()
    override var segmentsLoudnessMax: DoubleArray by Delegates.notNull()
    override var segmentsLoudnessMaxTime: DoubleArray by Delegates.notNull()
    override var segmentsLoudnessStart: DoubleArray by Delegates.notNull()
    override var sectionsStart: DoubleArray by Delegates.notNull()
    override var sectionsConfidence: DoubleArray by Delegates.notNull()
    override var beatsStart: DoubleArray by Delegates.notNull()
    override var beatsConfidence: DoubleArray by Delegates.notNull()
    override var barsStart: DoubleArray by Delegates.notNull()
    override var barsConfidence: DoubleArray by Delegates.notNull()
    override var tatumsStart: DoubleArray by Delegates.notNull()
    override var tatumsConfidence: DoubleArray by Delegates.notNull()
    override var year: Int by Delegates.notNull()
    override var artistMbTags: Array<String> by Delegates.notNull()
    override var artistMbTagsCount: IntArray by Delegates.notNull()

    override fun readFields(input: DataInput) {
        artistFamiliarity = input.readDouble()
        artistHotttnesss = input.readDouble()
        artistId = input.readUTF()
        artistMbId = input.readUTF()
        artistPlaymeId = input.readInt()
        artist7DigitalId = input.readInt()
        artistLatitude = input.readDouble()
        artistLongitude = input.readDouble()
        artistLocation = input.readUTF()
        artistName = input.readUTF()
        release = input.readUTF()
        release7DigitalId = input.readInt()
        songId = input.readUTF()
        songHotttnesss = input.readDouble()
        title = input.readUTF()
        track7DigitalId = input.readInt()
        similarArtists = input.readUTFArray()
        artistTerms = input.readUTFArray()
        artistTermsFrequency = input.readDoubleArray()
        artistTermsWeight = input.readDoubleArray()
        analysisSampleRate = input.readInt()
        audioMd5 = input.readUTF()
        danceability = input.readDouble()
        duration = input.readDouble()
        fadeInEnd = input.readDouble()
        energy = input.readDouble()
        key = input.readInt()
        keyConfidence = input.readDouble()
        loudness = input.readDouble()
        mode = input.readInt()
        modeConfidence = input.readDouble()
        fadeOutStart = input.readDouble()
        tempo = input.readDouble()
        timeSignature = input.readInt()
        timeSignatureConfidence = input.readDouble()
        trackId = input.readUTF()
        segmentsStart = input.readDoubleArray()
        segmentsConfidence = input.readDoubleArray()
        segmentsPitches = input.readDoubleArray()
        segmentsTimbre = input.readDoubleArray()
        segmentsLoudnessMax = input.readDoubleArray()
        segmentsLoudnessMaxTime = input.readDoubleArray()
        segmentsLoudnessStart = input.readDoubleArray()
        sectionsStart = input.readDoubleArray()
        sectionsConfidence = input.readDoubleArray()
        beatsStart = input.readDoubleArray()
        beatsConfidence = input.readDoubleArray()
        barsStart = input.readDoubleArray()
        barsConfidence = input.readDoubleArray()
        tatumsStart = input.readDoubleArray()
        tatumsConfidence = input.readDoubleArray()
        year = input.readInt()
        artistMbTags = input.readUTFArray()
        artistMbTagsCount = input.readIntArray()
    }

    override fun write(output: DataOutput) {
        output.writeDouble(artistFamiliarity)
        output.writeDouble(artistHotttnesss)
        output.writeUTF(artistId)
        output.writeUTF(artistMbId)
        output.writeInt(artistPlaymeId)
        output.writeInt(artist7DigitalId)
        output.writeDouble(artistLatitude)
        output.writeDouble(artistLongitude)
        output.writeUTF(artistLocation)
        output.writeUTF(artistName)
        output.writeUTF(release)
        output.writeInt(release7DigitalId)
        output.writeUTF(songId)
        output.writeDouble(songHotttnesss)
        output.writeUTF(title)
        output.writeInt(track7DigitalId)
        output.writeUTFArray(similarArtists)
        output.writeUTFArray(artistTerms)
        output.writeDoubleArray(artistTermsFrequency)
        output.writeDoubleArray(artistTermsWeight)
        output.writeInt(analysisSampleRate)
        output.writeUTF(audioMd5)
        output.writeDouble(danceability)
        output.writeDouble(duration)
        output.writeDouble(fadeInEnd)
        output.writeDouble(energy)
        output.writeInt(key)
        output.writeDouble(keyConfidence)
        output.writeDouble(loudness)
        output.writeInt(mode)
        output.writeDouble(modeConfidence)
        output.writeDouble(fadeOutStart)
        output.writeDouble(tempo)
        output.writeInt(timeSignature)
        output.writeDouble(timeSignatureConfidence)
        output.writeUTF(trackId)
        output.writeDoubleArray(segmentsStart)
        output.writeDoubleArray(segmentsConfidence)
        output.writeDoubleArray(segmentsPitches)
        output.writeDoubleArray(segmentsTimbre)
        output.writeDoubleArray(segmentsLoudnessMax)
        output.writeDoubleArray(segmentsLoudnessMaxTime)
        output.writeDoubleArray(segmentsLoudnessStart)
        output.writeDoubleArray(sectionsStart)
        output.writeDoubleArray(sectionsConfidence)
        output.writeDoubleArray(beatsStart)
        output.writeDoubleArray(beatsConfidence)
        output.writeDoubleArray(barsStart)
        output.writeDoubleArray(barsConfidence)
        output.writeDoubleArray(tatumsStart)
        output.writeDoubleArray(tatumsConfidence)
        output.writeInt(year)
        output.writeUTFArray(artistMbTags)
        output.writeIntArray(artistMbTagsCount)
    }
}